package com.aprotrain.sl.dal.entity;
// Generated Apr 15, 2015 8:50:37 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * BatchStudentList generated by hbm2java
 */
public class BatchStudentList  implements java.io.Serializable {


     private BatchStudentListId id;
     private Batch batch;
     private Student student;
     private Byte attendanceType;
     private Byte status;
     private Serializable remarks;
     private Byte gpaQ1;
     private Byte gpaQ2;
     private Byte gpaQ3;
     private Byte gpaQ4;
     private Byte gpaQ5;
     private Byte gpaQ6;
     private Serializable gpaRemarks;
     private Set batchAttendances = new HashSet(0);

    public BatchStudentList() {
    }

	
    public BatchStudentList(BatchStudentListId id, Batch batch, Student student) {
        this.id = id;
        this.batch = batch;
        this.student = student;
    }
    public BatchStudentList(BatchStudentListId id, Batch batch, Student student, Byte attendanceType, Byte status, Serializable remarks, Byte gpaQ1, Byte gpaQ2, Byte gpaQ3, Byte gpaQ4, Byte gpaQ5, Byte gpaQ6, Serializable gpaRemarks, Set batchAttendances) {
       this.id = id;
       this.batch = batch;
       this.student = student;
       this.attendanceType = attendanceType;
       this.status = status;
       this.remarks = remarks;
       this.gpaQ1 = gpaQ1;
       this.gpaQ2 = gpaQ2;
       this.gpaQ3 = gpaQ3;
       this.gpaQ4 = gpaQ4;
       this.gpaQ5 = gpaQ5;
       this.gpaQ6 = gpaQ6;
       this.gpaRemarks = gpaRemarks;
       this.batchAttendances = batchAttendances;
    }
   
    public BatchStudentListId getId() {
        return this.id;
    }
    
    public void setId(BatchStudentListId id) {
        this.id = id;
    }
    public Batch getBatch() {
        return this.batch;
    }
    
    public void setBatch(Batch batch) {
        this.batch = batch;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Byte getAttendanceType() {
        return this.attendanceType;
    }
    
    public void setAttendanceType(Byte attendanceType) {
        this.attendanceType = attendanceType;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public Serializable getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(Serializable remarks) {
        this.remarks = remarks;
    }
    public Byte getGpaQ1() {
        return this.gpaQ1;
    }
    
    public void setGpaQ1(Byte gpaQ1) {
        this.gpaQ1 = gpaQ1;
    }
    public Byte getGpaQ2() {
        return this.gpaQ2;
    }
    
    public void setGpaQ2(Byte gpaQ2) {
        this.gpaQ2 = gpaQ2;
    }
    public Byte getGpaQ3() {
        return this.gpaQ3;
    }
    
    public void setGpaQ3(Byte gpaQ3) {
        this.gpaQ3 = gpaQ3;
    }
    public Byte getGpaQ4() {
        return this.gpaQ4;
    }
    
    public void setGpaQ4(Byte gpaQ4) {
        this.gpaQ4 = gpaQ4;
    }
    public Byte getGpaQ5() {
        return this.gpaQ5;
    }
    
    public void setGpaQ5(Byte gpaQ5) {
        this.gpaQ5 = gpaQ5;
    }
    public Byte getGpaQ6() {
        return this.gpaQ6;
    }
    
    public void setGpaQ6(Byte gpaQ6) {
        this.gpaQ6 = gpaQ6;
    }
    public Serializable getGpaRemarks() {
        return this.gpaRemarks;
    }
    
    public void setGpaRemarks(Serializable gpaRemarks) {
        this.gpaRemarks = gpaRemarks;
    }
    public Set getBatchAttendances() {
        return this.batchAttendances;
    }
    
    public void setBatchAttendances(Set batchAttendances) {
        this.batchAttendances = batchAttendances;
    }




}


