package com.aprotrain.sl.dal.entity;
// Generated Apr 15, 2015 8:50:37 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * BatchSession generated by hbm2java
 */
public class BatchSession  implements java.io.Serializable {


     private BatchSessionId id;
     private Batch batch;
     private FacultyDetails facultyDetails;
     private Serializable remarks;
     private Byte duration;
     private Byte sessionType;
     private Set batchAttendances = new HashSet(0);

    public BatchSession() {
    }

	
    public BatchSession(BatchSessionId id, Batch batch) {
        this.id = id;
        this.batch = batch;
    }
    public BatchSession(BatchSessionId id, Batch batch, FacultyDetails facultyDetails, Serializable remarks, Byte duration, Byte sessionType, Set batchAttendances) {
       this.id = id;
       this.batch = batch;
       this.facultyDetails = facultyDetails;
       this.remarks = remarks;
       this.duration = duration;
       this.sessionType = sessionType;
       this.batchAttendances = batchAttendances;
    }
   
    public BatchSessionId getId() {
        return this.id;
    }
    
    public void setId(BatchSessionId id) {
        this.id = id;
    }
    public Batch getBatch() {
        return this.batch;
    }
    
    public void setBatch(Batch batch) {
        this.batch = batch;
    }
    public FacultyDetails getFacultyDetails() {
        return this.facultyDetails;
    }
    
    public void setFacultyDetails(FacultyDetails facultyDetails) {
        this.facultyDetails = facultyDetails;
    }
    public Serializable getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(Serializable remarks) {
        this.remarks = remarks;
    }
    public Byte getDuration() {
        return this.duration;
    }
    
    public void setDuration(Byte duration) {
        this.duration = duration;
    }
    public Byte getSessionType() {
        return this.sessionType;
    }
    
    public void setSessionType(Byte sessionType) {
        this.sessionType = sessionType;
    }
    public Set getBatchAttendances() {
        return this.batchAttendances;
    }
    
    public void setBatchAttendances(Set batchAttendances) {
        this.batchAttendances = batchAttendances;
    }




}


