package com.aprotrain.sl.dal.entity;
// Generated Apr 18, 2015 3:08:48 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * BatchAttendance generated by hbm2java
 */
public class BatchAttendance  implements java.io.Serializable {


     private BatchAttendanceId id;
     private BatchSession batchSession;
     private BatchStudentList batchStudentList;
     private Byte attendanceType;
     private Serializable remarks;

    public BatchAttendance() {
    }

	
    public BatchAttendance(BatchAttendanceId id, BatchSession batchSession, BatchStudentList batchStudentList) {
        this.id = id;
        this.batchSession = batchSession;
        this.batchStudentList = batchStudentList;
    }
    public BatchAttendance(BatchAttendanceId id, BatchSession batchSession, BatchStudentList batchStudentList, Byte attendanceType, Serializable remarks) {
       this.id = id;
       this.batchSession = batchSession;
       this.batchStudentList = batchStudentList;
       this.attendanceType = attendanceType;
       this.remarks = remarks;
    }
   
    public BatchAttendanceId getId() {
        return this.id;
    }
    
    public void setId(BatchAttendanceId id) {
        this.id = id;
    }
    public BatchSession getBatchSession() {
        return this.batchSession;
    }
    
    public void setBatchSession(BatchSession batchSession) {
        this.batchSession = batchSession;
    }
    public BatchStudentList getBatchStudentList() {
        return this.batchStudentList;
    }
    
    public void setBatchStudentList(BatchStudentList batchStudentList) {
        this.batchStudentList = batchStudentList;
    }
    public Byte getAttendanceType() {
        return this.attendanceType;
    }
    
    public void setAttendanceType(Byte attendanceType) {
        this.attendanceType = attendanceType;
    }
    public Serializable getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(Serializable remarks) {
        this.remarks = remarks;
    }




}


