package com.aprotrain.sl.dal.entity;
// Generated Apr 15, 2015 8:50:37 PM by Hibernate Tools 4.3.1



/**
 * BatchStudentListId generated by hbm2java
 */
public class BatchStudentListId  implements java.io.Serializable {


     private long batchId;
     private long studentId;

    public BatchStudentListId() {
    }

    public BatchStudentListId(long batchId, long studentId) {
       this.batchId = batchId;
       this.studentId = studentId;
    }
   
    public long getBatchId() {
        return this.batchId;
    }
    
    public void setBatchId(long batchId) {
        this.batchId = batchId;
    }
    public long getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(long studentId) {
        this.studentId = studentId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BatchStudentListId) ) return false;
		 BatchStudentListId castOther = ( BatchStudentListId ) other; 
         
		 return (this.getBatchId()==castOther.getBatchId())
 && (this.getStudentId()==castOther.getStudentId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getBatchId();
         result = 37 * result + (int) this.getStudentId();
         return result;
   }   


}


