package com.aprotrain.sl.dal.entity;
// Generated Apr 15, 2015 8:50:37 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Batch generated by hbm2java
 */
public class Batch  implements java.io.Serializable {


     private long batchId;
     private ClassUnit classUnit;
     private FacultyDetails facultyDetails;
     private Subject subject;
     private Serializable gpaDate;
     private Serializable startDate;
     private byte batchStatus;
     private Set batchStudentLists = new HashSet(0);
     private Set batchSessions = new HashSet(0);

    public Batch() {
    }

	
    public Batch(long batchId, ClassUnit classUnit, Subject subject, Serializable startDate, byte batchStatus) {
        this.batchId = batchId;
        this.classUnit = classUnit;
        this.subject = subject;
        this.startDate = startDate;
        this.batchStatus = batchStatus;
    }
    public Batch(long batchId, ClassUnit classUnit, FacultyDetails facultyDetails, Subject subject, Serializable gpaDate, Serializable startDate, byte batchStatus, Set batchStudentLists, Set batchSessions) {
       this.batchId = batchId;
       this.classUnit = classUnit;
       this.facultyDetails = facultyDetails;
       this.subject = subject;
       this.gpaDate = gpaDate;
       this.startDate = startDate;
       this.batchStatus = batchStatus;
       this.batchStudentLists = batchStudentLists;
       this.batchSessions = batchSessions;
    }
   
    public long getBatchId() {
        return this.batchId;
    }
    
    public void setBatchId(long batchId) {
        this.batchId = batchId;
    }
    public ClassUnit getClassUnit() {
        return this.classUnit;
    }
    
    public void setClassUnit(ClassUnit classUnit) {
        this.classUnit = classUnit;
    }
    public FacultyDetails getFacultyDetails() {
        return this.facultyDetails;
    }
    
    public void setFacultyDetails(FacultyDetails facultyDetails) {
        this.facultyDetails = facultyDetails;
    }
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }
    public Serializable getGpaDate() {
        return this.gpaDate;
    }
    
    public void setGpaDate(Serializable gpaDate) {
        this.gpaDate = gpaDate;
    }
    public Serializable getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Serializable startDate) {
        this.startDate = startDate;
    }
    public byte getBatchStatus() {
        return this.batchStatus;
    }
    
    public void setBatchStatus(byte batchStatus) {
        this.batchStatus = batchStatus;
    }
    public Set getBatchStudentLists() {
        return this.batchStudentLists;
    }
    
    public void setBatchStudentLists(Set batchStudentLists) {
        this.batchStudentLists = batchStudentLists;
    }
    public Set getBatchSessions() {
        return this.batchSessions;
    }
    
    public void setBatchSessions(Set batchSessions) {
        this.batchSessions = batchSessions;
    }




}


