package com.aprotrain.sl.dal.entity;
// Generated Apr 18, 2015 3:08:48 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * BatchSession generated by hbm2java
 */
public class BatchSession  implements java.io.Serializable {


     private BatchSessionId id;
     private Batch batch;
     private Serializable remarks;
     private Long subFaculty;
     private Byte duration;
     private Byte sessionType;
     private Set batchAttendances = new HashSet(0);

    public BatchSession() {
    }

	
    public BatchSession(BatchSessionId id, Batch batch) {
        this.id = id;
        this.batch = batch;
    }
    public BatchSession(BatchSessionId id, Batch batch, Serializable remarks, Long subFaculty, Byte duration, Byte sessionType, Set batchAttendances) {
       this.id = id;
       this.batch = batch;
       this.remarks = remarks;
       this.subFaculty = subFaculty;
       this.duration = duration;
       this.sessionType = sessionType;
       this.batchAttendances = batchAttendances;
    }
   
    public BatchSessionId getId() {
        return this.id;
    }
    
    public void setId(BatchSessionId id) {
        this.id = id;
    }
    public Batch getBatch() {
        return this.batch;
    }
    
    public void setBatch(Batch batch) {
        this.batch = batch;
    }
    public Serializable getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(Serializable remarks) {
        this.remarks = remarks;
    }
    public Long getSubFaculty() {
        return this.subFaculty;
    }
    
    public void setSubFaculty(Long subFaculty) {
        this.subFaculty = subFaculty;
    }
    public Byte getDuration() {
        return this.duration;
    }
    
    public void setDuration(Byte duration) {
        this.duration = duration;
    }
    public Byte getSessionType() {
        return this.sessionType;
    }
    
    public void setSessionType(Byte sessionType) {
        this.sessionType = sessionType;
    }
    public Set getBatchAttendances() {
        return this.batchAttendances;
    }
    
    public void setBatchAttendances(Set batchAttendances) {
        this.batchAttendances = batchAttendances;
    }




}


