package com.aprotrain.sl.dal.entity;
// Generated Mar 27, 2015 2:04:37 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Batch generated by hbm2java
 */
public class Batch  implements java.io.Serializable {


     private int batchId;
     private Faculty faculty;
     private Subject subject;
     private Serializable gpaDate;
     private Serializable startDate;

    public Batch() {
    }

	
    public Batch(int batchId) {
        this.batchId = batchId;
    }
    public Batch(int batchId, Faculty faculty, Subject subject, Serializable gpaDate, Serializable startDate) {
       this.batchId = batchId;
       this.faculty = faculty;
       this.subject = subject;
       this.gpaDate = gpaDate;
       this.startDate = startDate;
    }
   
    public int getBatchId() {
        return this.batchId;
    }
    
    public void setBatchId(int batchId) {
        this.batchId = batchId;
    }
    public Faculty getFaculty() {
        return this.faculty;
    }
    
    public void setFaculty(Faculty faculty) {
        this.faculty = faculty;
    }
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }
    public Serializable getGpaDate() {
        return this.gpaDate;
    }
    
    public void setGpaDate(Serializable gpaDate) {
        this.gpaDate = gpaDate;
    }
    public Serializable getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Serializable startDate) {
        this.startDate = startDate;
    }




}


