package com.aprotrain.sl.dal.entity;
// Generated Apr 15, 2015 8:50:37 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * ClassOpenHouse generated by hbm2java
 */
public class ClassOpenHouse  implements java.io.Serializable {


     private ClassOpenHouseId id;
     private ClassUnit classUnit;
     private Serializable title;
     private Byte openHouseStatus;
     private Serializable openHouseDate;

    public ClassOpenHouse() {
    }

	
    public ClassOpenHouse(ClassOpenHouseId id, ClassUnit classUnit) {
        this.id = id;
        this.classUnit = classUnit;
    }
    public ClassOpenHouse(ClassOpenHouseId id, ClassUnit classUnit, Serializable title, Byte openHouseStatus, Serializable openHouseDate) {
       this.id = id;
       this.classUnit = classUnit;
       this.title = title;
       this.openHouseStatus = openHouseStatus;
       this.openHouseDate = openHouseDate;
    }
   
    public ClassOpenHouseId getId() {
        return this.id;
    }
    
    public void setId(ClassOpenHouseId id) {
        this.id = id;
    }
    public ClassUnit getClassUnit() {
        return this.classUnit;
    }
    
    public void setClassUnit(ClassUnit classUnit) {
        this.classUnit = classUnit;
    }
    public Serializable getTitle() {
        return this.title;
    }
    
    public void setTitle(Serializable title) {
        this.title = title;
    }
    public Byte getOpenHouseStatus() {
        return this.openHouseStatus;
    }
    
    public void setOpenHouseStatus(Byte openHouseStatus) {
        this.openHouseStatus = openHouseStatus;
    }
    public Serializable getOpenHouseDate() {
        return this.openHouseDate;
    }
    
    public void setOpenHouseDate(Serializable openHouseDate) {
        this.openHouseDate = openHouseDate;
    }




}


