package com.aprotrain.sl.dal.entity;
// Generated Apr 18, 2015 3:08:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ClassUnit generated by hbm2java
 */
public class ClassUnit  implements java.io.Serializable {


     private long classId;
     private String className;
     private Date startDate;
     private String classStatus;
     private Set studentsForCurrentClass = new HashSet(0);
     private Set studentsForInitClass = new HashSet(0);
     private Set classOpenHouses = new HashSet(0);

    public ClassUnit() {
    }


    public ClassUnit(long classId) {
        this.classId = classId;
    }
    public ClassUnit(long classId, String className, Date startDate, String classStatus, Set studentsForCurrentClass, Set studentsForInitClass, Set classOpenHouses) {
       this.classId = classId;
       this.className = className;
       this.startDate = startDate;
       this.classStatus = classStatus;
       this.studentsForCurrentClass = studentsForCurrentClass;
       this.studentsForInitClass = studentsForInitClass;
       this.classOpenHouses = classOpenHouses;
    }

    public long getClassId() {
        return this.classId;
    }

    public void setClassId(long classId) {
        this.classId = classId;
    }
    public String getClassName() {
        return this.className;
    }

    public void setClassName(String className) {
        this.className = className;
    }
    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public String getClassStatus() {
        return this.classStatus;
    }

    public void setClassStatus(String classStatus) {
        this.classStatus = classStatus;
    }
    public Set getStudentsForCurrentClass() {
        return this.studentsForCurrentClass;
    }

    public void setStudentsForCurrentClass(Set studentsForCurrentClass) {
        this.studentsForCurrentClass = studentsForCurrentClass;
    }
    public Set getStudentsForInitClass() {
        return this.studentsForInitClass;
    }

    public void setStudentsForInitClass(Set studentsForInitClass) {
        this.studentsForInitClass = studentsForInitClass;
    }
    public Set getClassOpenHouses() {
        return this.classOpenHouses;
    }

    public void setClassOpenHouses(Set classOpenHouses) {
        this.classOpenHouses = classOpenHouses;
    }




}


