package com.aprotrain.sl.dal.entity;
// Generated Apr 18, 2015 3:08:48 PM by Hibernate Tools 4.3.1



/**
 * ClassOpenHouseId generated by hbm2java
 */
public class ClassOpenHouseId  implements java.io.Serializable {


     private long classId;
     private String openHouseMonth;

    public ClassOpenHouseId() {
    }

    public ClassOpenHouseId(long classId, String openHouseMonth) {
       this.classId = classId;
       this.openHouseMonth = openHouseMonth;
    }
   
    public long getClassId() {
        return this.classId;
    }
    
    public void setClassId(long classId) {
        this.classId = classId;
    }
    public String getOpenHouseMonth() {
        return this.openHouseMonth;
    }
    
    public void setOpenHouseMonth(String openHouseMonth) {
        this.openHouseMonth = openHouseMonth;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClassOpenHouseId) ) return false;
		 ClassOpenHouseId castOther = ( ClassOpenHouseId ) other; 
         
		 return (this.getClassId()==castOther.getClassId())
 && ( (this.getOpenHouseMonth()==castOther.getOpenHouseMonth()) || ( this.getOpenHouseMonth()!=null && castOther.getOpenHouseMonth()!=null && this.getOpenHouseMonth().equals(castOther.getOpenHouseMonth()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getClassId();
         result = 37 * result + ( getOpenHouseMonth() == null ? 0 : this.getOpenHouseMonth().hashCode() );
         return result;
   }   


}


