package com.aprotrain.sl.dal.entity;
// Generated Apr 15, 2015 8:50:37 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * ClassUnit generated by hbm2java
 */
public class ClassUnit  implements java.io.Serializable {


     private long classId;
     private String className;
     private Serializable startDate;
     private String classStatus;
     private Set classOpenHouses = new HashSet(0);
     private Set batches = new HashSet(0);
     private Set studentsForInitClass = new HashSet(0);
     private Set studentsForCurrentClass = new HashSet(0);

    public ClassUnit() {
    }

	
    public ClassUnit(long classId) {
        this.classId = classId;
    }
    public ClassUnit(long classId, String className, Serializable startDate, String classStatus, Set classOpenHouses, Set batches, Set studentsForInitClass, Set studentsForCurrentClass) {
       this.classId = classId;
       this.className = className;
       this.startDate = startDate;
       this.classStatus = classStatus;
       this.classOpenHouses = classOpenHouses;
       this.batches = batches;
       this.studentsForInitClass = studentsForInitClass;
       this.studentsForCurrentClass = studentsForCurrentClass;
    }
   
    public long getClassId() {
        return this.classId;
    }
    
    public void setClassId(long classId) {
        this.classId = classId;
    }
    public String getClassName() {
        return this.className;
    }
    
    public void setClassName(String className) {
        this.className = className;
    }
    public Serializable getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Serializable startDate) {
        this.startDate = startDate;
    }
    public String getClassStatus() {
        return this.classStatus;
    }
    
    public void setClassStatus(String classStatus) {
        this.classStatus = classStatus;
    }
    public Set getClassOpenHouses() {
        return this.classOpenHouses;
    }
    
    public void setClassOpenHouses(Set classOpenHouses) {
        this.classOpenHouses = classOpenHouses;
    }
    public Set getBatches() {
        return this.batches;
    }
    
    public void setBatches(Set batches) {
        this.batches = batches;
    }
    public Set getStudentsForInitClass() {
        return this.studentsForInitClass;
    }
    
    public void setStudentsForInitClass(Set studentsForInitClass) {
        this.studentsForInitClass = studentsForInitClass;
    }
    public Set getStudentsForCurrentClass() {
        return this.studentsForCurrentClass;
    }
    
    public void setStudentsForCurrentClass(Set studentsForCurrentClass) {
        this.studentsForCurrentClass = studentsForCurrentClass;
    }




}


