package com.aprotrain.sl.dal.entity;
// Generated Mar 27, 2015 2:04:37 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Clazz generated by hbm2java
 */
public class Clazz  implements java.io.Serializable {


     private int classId;
     private Course course;
     private String className;
     private Serializable startDate;
     private Integer status;
     private Set studentsForCurrentClass = new HashSet(0);
     private Set studentsForInitClass = new HashSet(0);

    public Clazz() {
    }

	
    public Clazz(int classId) {
        this.classId = classId;
    }
    public Clazz(int classId, Course course, String className, Serializable startDate, Integer status, Set studentsForCurrentClass, Set studentsForInitClass) {
       this.classId = classId;
       this.course = course;
       this.className = className;
       this.startDate = startDate;
       this.status = status;
       this.studentsForCurrentClass = studentsForCurrentClass;
       this.studentsForInitClass = studentsForInitClass;
    }
   
    public int getClassId() {
        return this.classId;
    }
    
    public void setClassId(int classId) {
        this.classId = classId;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public String getClassName() {
        return this.className;
    }
    
    public void setClassName(String className) {
        this.className = className;
    }
    public Serializable getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Serializable startDate) {
        this.startDate = startDate;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getStudentsForCurrentClass() {
        return this.studentsForCurrentClass;
    }
    
    public void setStudentsForCurrentClass(Set studentsForCurrentClass) {
        this.studentsForCurrentClass = studentsForCurrentClass;
    }
    public Set getStudentsForInitClass() {
        return this.studentsForInitClass;
    }
    
    public void setStudentsForInitClass(Set studentsForInitClass) {
        this.studentsForInitClass = studentsForInitClass;
    }




}


