package com.aprotrain.sl.dal.entity;
// Generated Apr 17, 2015 12:45:39 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private long courseId;
     private Serializable courseCode;
     private Integer year;
     private Serializable remarks;
     private Byte status;
     private Set students = new HashSet(0);
     private Set subjects = new HashSet(0);

    public Course() {
    }

	
    public Course(long courseId, Serializable courseCode) {
        this.courseId = courseId;
        this.courseCode = courseCode;
    }
    public Course(long courseId, Serializable courseCode, Integer year, Serializable remarks, Byte status, Set students, Set subjects) {
       this.courseId = courseId;
       this.courseCode = courseCode;
       this.year = year;
       this.remarks = remarks;
       this.status = status;
       this.students = students;
       this.subjects = subjects;
    }
   
    public long getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(long courseId) {
        this.courseId = courseId;
    }
    public Serializable getCourseCode() {
        return this.courseCode;
    }
    
    public void setCourseCode(Serializable courseCode) {
        this.courseCode = courseCode;
    }
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    public Serializable getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(Serializable remarks) {
        this.remarks = remarks;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public Set getStudents() {
        return this.students;
    }
    
    public void setStudents(Set students) {
        this.students = students;
    }
    public Set getSubjects() {
        return this.subjects;
    }
    
    public void setSubjects(Set subjects) {
        this.subjects = subjects;
    }




}


