package com.aprotrain.sl.dal.entity;
// Generated Mar 27, 2015 2:04:37 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private int courseId;
     private Serializable courseCode;
     private Integer year;
     private Serializable remarks;
     private Set clazzs = new HashSet(0);
     private Set subjects = new HashSet(0);

    public Course() {
    }

	
    public Course(int courseId, Serializable courseCode) {
        this.courseId = courseId;
        this.courseCode = courseCode;
    }
    public Course(int courseId, Serializable courseCode, Integer year, Serializable remarks, Set clazzs, Set subjects) {
       this.courseId = courseId;
       this.courseCode = courseCode;
       this.year = year;
       this.remarks = remarks;
       this.clazzs = clazzs;
       this.subjects = subjects;
    }
   
    public int getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(int courseId) {
        this.courseId = courseId;
    }
    public Serializable getCourseCode() {
        return this.courseCode;
    }
    
    public void setCourseCode(Serializable courseCode) {
        this.courseCode = courseCode;
    }
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    public Serializable getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(Serializable remarks) {
        this.remarks = remarks;
    }
    public Set getClazzs() {
        return this.clazzs;
    }
    
    public void setClazzs(Set clazzs) {
        this.clazzs = clazzs;
    }
    public Set getSubjects() {
        return this.subjects;
    }
    
    public void setSubjects(Set subjects) {
        this.subjects = subjects;
    }




}


