package com.aprotrain.sl.dal.entity;
// Generated Mar 31, 2015 2:57:52 PM by Hibernate Tools 4.3.1

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private int employeeId;
     private String fullname;
     private String socialId;
     private String internalEmail;
     private String externalEmail;
     private String dob;
     private String joiningDate;
     private String password;

    public Employee() {
    }


    public Employee(int employeeId) {
        this.employeeId = employeeId;
    }
    public Employee(int employeeId, String fullname, String socialId, String internalEmail, String externalEmail, String dob, String joiningDate, String password) {
       this.employeeId = employeeId;
       this.fullname = fullname;
       this.socialId = socialId;
       this.internalEmail = internalEmail;
       this.externalEmail = externalEmail;
       this.dob = dob;
       this.joiningDate = joiningDate;
       this.password = password;
    }

    public int getEmployeeId() {
        return this.employeeId;
    }

    public void setEmployeeId(int employeeId) {
        this.employeeId = employeeId;
    }
    public String getFullname() {
        return this.fullname;
    }

    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getSocialId() {
        return this.socialId;
    }

    public void setSocialId(String socialId) {
        this.socialId = socialId;
    }
    public String getInternalEmail() {
        return this.internalEmail;
    }

    public void setInternalEmail(String internalEmail) {
        this.internalEmail = internalEmail;
    }
    public String getExternalEmail() {
        return this.externalEmail;
    }

    public void setExternalEmail(String externalEmail) {
        this.externalEmail = externalEmail;
    }
    public String getDob() {
        return this.dob;
    }

    public void setDob(String dob) {
        this.dob = dob;
    }
    public String getJoiningDate() {
        return this.joiningDate;
    }

    public void setJoiningDate(String joiningDate) {
        this.joiningDate = joiningDate;
    }
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }




}


