package com.aprotrain.sl.dal.entity;
// Generated Mar 27, 2015 2:04:37 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private int employeeId;
     private Serializable fullname;
     private Serializable idNo;
     private Serializable internalEmail;
     private Serializable externalEmail;
     private Serializable dob;
     private Serializable joiningDate;
     private Set faculties = new HashSet(0);

    public Employee() {
    }

	
    public Employee(int employeeId) {
        this.employeeId = employeeId;
    }
    public Employee(int employeeId, Serializable fullname, Serializable idNo, Serializable internalEmail, Serializable externalEmail, Serializable dob, Serializable joiningDate, Set faculties) {
       this.employeeId = employeeId;
       this.fullname = fullname;
       this.idNo = idNo;
       this.internalEmail = internalEmail;
       this.externalEmail = externalEmail;
       this.dob = dob;
       this.joiningDate = joiningDate;
       this.faculties = faculties;
    }
   
    public int getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(int employeeId) {
        this.employeeId = employeeId;
    }
    public Serializable getFullname() {
        return this.fullname;
    }
    
    public void setFullname(Serializable fullname) {
        this.fullname = fullname;
    }
    public Serializable getIdNo() {
        return this.idNo;
    }
    
    public void setIdNo(Serializable idNo) {
        this.idNo = idNo;
    }
    public Serializable getInternalEmail() {
        return this.internalEmail;
    }
    
    public void setInternalEmail(Serializable internalEmail) {
        this.internalEmail = internalEmail;
    }
    public Serializable getExternalEmail() {
        return this.externalEmail;
    }
    
    public void setExternalEmail(Serializable externalEmail) {
        this.externalEmail = externalEmail;
    }
    public Serializable getDob() {
        return this.dob;
    }
    
    public void setDob(Serializable dob) {
        this.dob = dob;
    }
    public Serializable getJoiningDate() {
        return this.joiningDate;
    }
    
    public void setJoiningDate(Serializable joiningDate) {
        this.joiningDate = joiningDate;
    }
    public Set getFaculties() {
        return this.faculties;
    }
    
    public void setFaculties(Set faculties) {
        this.faculties = faculties;
    }




}


