package com.aprotrain.sl.dal.entity;
// Generated Apr 18, 2015 3:08:48 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private long employeeId;
     private Serializable fullname;
     private Serializable socialId;
     private Serializable internalEmail;
     private Serializable externalEmail;
     private Serializable dob;
     private Serializable joiningDate;
     private String password;
     private Byte employeeStatus;
     private Set facultyDetailses = new HashSet(0);

    public Employee() {
    }

	
    public Employee(long employeeId) {
        this.employeeId = employeeId;
    }
    public Employee(long employeeId, Serializable fullname, Serializable socialId, Serializable internalEmail, Serializable externalEmail, Serializable dob, Serializable joiningDate, String password, Byte employeeStatus, Set facultyDetailses) {
       this.employeeId = employeeId;
       this.fullname = fullname;
       this.socialId = socialId;
       this.internalEmail = internalEmail;
       this.externalEmail = externalEmail;
       this.dob = dob;
       this.joiningDate = joiningDate;
       this.password = password;
       this.employeeStatus = employeeStatus;
       this.facultyDetailses = facultyDetailses;
    }
   
    public long getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(long employeeId) {
        this.employeeId = employeeId;
    }
    public Serializable getFullname() {
        return this.fullname;
    }
    
    public void setFullname(Serializable fullname) {
        this.fullname = fullname;
    }
    public Serializable getSocialId() {
        return this.socialId;
    }
    
    public void setSocialId(Serializable socialId) {
        this.socialId = socialId;
    }
    public Serializable getInternalEmail() {
        return this.internalEmail;
    }
    
    public void setInternalEmail(Serializable internalEmail) {
        this.internalEmail = internalEmail;
    }
    public Serializable getExternalEmail() {
        return this.externalEmail;
    }
    
    public void setExternalEmail(Serializable externalEmail) {
        this.externalEmail = externalEmail;
    }
    public Serializable getDob() {
        return this.dob;
    }
    
    public void setDob(Serializable dob) {
        this.dob = dob;
    }
    public Serializable getJoiningDate() {
        return this.joiningDate;
    }
    
    public void setJoiningDate(Serializable joiningDate) {
        this.joiningDate = joiningDate;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Byte getEmployeeStatus() {
        return this.employeeStatus;
    }
    
    public void setEmployeeStatus(Byte employeeStatus) {
        this.employeeStatus = employeeStatus;
    }
    public Set getFacultyDetailses() {
        return this.facultyDetailses;
    }
    
    public void setFacultyDetailses(Set facultyDetailses) {
        this.facultyDetailses = facultyDetailses;
    }




}


