package com.aprotrain.sl.dal.entity;
// Generated Apr 18, 2015 3:08:48 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Exam generated by hbm2java
 */
public class Exam  implements java.io.Serializable {


     private long examId;
     private Batch batch;
     private Subject subject;
     private Serializable examDate;
     private Character timeSlot;
     private Byte examType;
     private Long supervisory;
     private Long fcReview;
     private Long fcCheck;
     private Serializable passRate;
     private Serializable remarks;
     private Serializable fcCheckDate;
     private Serializable fcReviewDate;
     private String examFile;
     private String resultFile;
     private String reviewFile;
     private Set examAttendances = new HashSet(0);

    public Exam() {
    }

	
    public Exam(long examId) {
        this.examId = examId;
    }
    public Exam(long examId, Batch batch, Subject subject, Serializable examDate, Character timeSlot, Byte examType, Long supervisory, Long fcReview, Long fcCheck, Serializable passRate, Serializable remarks, Serializable fcCheckDate, Serializable fcReviewDate, String examFile, String resultFile, String reviewFile, Set examAttendances) {
       this.examId = examId;
       this.batch = batch;
       this.subject = subject;
       this.examDate = examDate;
       this.timeSlot = timeSlot;
       this.examType = examType;
       this.supervisory = supervisory;
       this.fcReview = fcReview;
       this.fcCheck = fcCheck;
       this.passRate = passRate;
       this.remarks = remarks;
       this.fcCheckDate = fcCheckDate;
       this.fcReviewDate = fcReviewDate;
       this.examFile = examFile;
       this.resultFile = resultFile;
       this.reviewFile = reviewFile;
       this.examAttendances = examAttendances;
    }
   
    public long getExamId() {
        return this.examId;
    }
    
    public void setExamId(long examId) {
        this.examId = examId;
    }
    public Batch getBatch() {
        return this.batch;
    }
    
    public void setBatch(Batch batch) {
        this.batch = batch;
    }
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }
    public Serializable getExamDate() {
        return this.examDate;
    }
    
    public void setExamDate(Serializable examDate) {
        this.examDate = examDate;
    }
    public Character getTimeSlot() {
        return this.timeSlot;
    }
    
    public void setTimeSlot(Character timeSlot) {
        this.timeSlot = timeSlot;
    }
    public Byte getExamType() {
        return this.examType;
    }
    
    public void setExamType(Byte examType) {
        this.examType = examType;
    }
    public Long getSupervisory() {
        return this.supervisory;
    }
    
    public void setSupervisory(Long supervisory) {
        this.supervisory = supervisory;
    }
    public Long getFcReview() {
        return this.fcReview;
    }
    
    public void setFcReview(Long fcReview) {
        this.fcReview = fcReview;
    }
    public Long getFcCheck() {
        return this.fcCheck;
    }
    
    public void setFcCheck(Long fcCheck) {
        this.fcCheck = fcCheck;
    }
    public Serializable getPassRate() {
        return this.passRate;
    }
    
    public void setPassRate(Serializable passRate) {
        this.passRate = passRate;
    }
    public Serializable getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(Serializable remarks) {
        this.remarks = remarks;
    }
    public Serializable getFcCheckDate() {
        return this.fcCheckDate;
    }
    
    public void setFcCheckDate(Serializable fcCheckDate) {
        this.fcCheckDate = fcCheckDate;
    }
    public Serializable getFcReviewDate() {
        return this.fcReviewDate;
    }
    
    public void setFcReviewDate(Serializable fcReviewDate) {
        this.fcReviewDate = fcReviewDate;
    }
    public String getExamFile() {
        return this.examFile;
    }
    
    public void setExamFile(String examFile) {
        this.examFile = examFile;
    }
    public String getResultFile() {
        return this.resultFile;
    }
    
    public void setResultFile(String resultFile) {
        this.resultFile = resultFile;
    }
    public String getReviewFile() {
        return this.reviewFile;
    }
    
    public void setReviewFile(String reviewFile) {
        this.reviewFile = reviewFile;
    }
    public Set getExamAttendances() {
        return this.examAttendances;
    }
    
    public void setExamAttendances(Set examAttendances) {
        this.examAttendances = examAttendances;
    }




}


