package com.aprotrain.sl.dal.entity;
// Generated Apr 15, 2015 8:50:37 PM by Hibernate Tools 4.3.1



/**
 * ExamAttendanceId generated by hbm2java
 */
public class ExamAttendanceId  implements java.io.Serializable {


     private long examId;
     private long studentId;

    public ExamAttendanceId() {
    }

    public ExamAttendanceId(long examId, long studentId) {
       this.examId = examId;
       this.studentId = studentId;
    }
   
    public long getExamId() {
        return this.examId;
    }
    
    public void setExamId(long examId) {
        this.examId = examId;
    }
    public long getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(long studentId) {
        this.studentId = studentId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ExamAttendanceId) ) return false;
		 ExamAttendanceId castOther = ( ExamAttendanceId ) other; 
         
		 return (this.getExamId()==castOther.getExamId())
 && (this.getStudentId()==castOther.getStudentId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getExamId();
         result = 37 * result + (int) this.getStudentId();
         return result;
   }   


}


