package com.aprotrain.sl.dal.entity;
// Generated Apr 15, 2015 8:50:37 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * ExamAttendance generated by hbm2java
 */
public class ExamAttendance  implements java.io.Serializable {


     private ExamAttendanceId id;
     private Exam exam;
     private Student student;
     private Byte examAttendanceStatus;
     private Byte takeTime;
     private String lab;
     private Serializable remarks;
     private Byte roomId;

    public ExamAttendance() {
    }

	
    public ExamAttendance(ExamAttendanceId id, Exam exam, Student student) {
        this.id = id;
        this.exam = exam;
        this.student = student;
    }
    public ExamAttendance(ExamAttendanceId id, Exam exam, Student student, Byte examAttendanceStatus, Byte takeTime, String lab, Serializable remarks, Byte roomId) {
       this.id = id;
       this.exam = exam;
       this.student = student;
       this.examAttendanceStatus = examAttendanceStatus;
       this.takeTime = takeTime;
       this.lab = lab;
       this.remarks = remarks;
       this.roomId = roomId;
    }
   
    public ExamAttendanceId getId() {
        return this.id;
    }
    
    public void setId(ExamAttendanceId id) {
        this.id = id;
    }
    public Exam getExam() {
        return this.exam;
    }
    
    public void setExam(Exam exam) {
        this.exam = exam;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Byte getExamAttendanceStatus() {
        return this.examAttendanceStatus;
    }
    
    public void setExamAttendanceStatus(Byte examAttendanceStatus) {
        this.examAttendanceStatus = examAttendanceStatus;
    }
    public Byte getTakeTime() {
        return this.takeTime;
    }
    
    public void setTakeTime(Byte takeTime) {
        this.takeTime = takeTime;
    }
    public String getLab() {
        return this.lab;
    }
    
    public void setLab(String lab) {
        this.lab = lab;
    }
    public Serializable getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(Serializable remarks) {
        this.remarks = remarks;
    }
    public Byte getRoomId() {
        return this.roomId;
    }
    
    public void setRoomId(Byte roomId) {
        this.roomId = roomId;
    }




}


