package com.aprotrain.sl.dal.entity;
// Generated Apr 15, 2015 8:50:37 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * FacultyDetails generated by hbm2java
 */
public class FacultyDetails  implements java.io.Serializable {


     private long facultyId;
     private Employee employee;
     private Serializable domain;
     private Byte quota;
     private String facultyType;
     private Set batchSessions = new HashSet(0);
     private Set batches = new HashSet(0);

    public FacultyDetails() {
    }

	
    public FacultyDetails(long facultyId) {
        this.facultyId = facultyId;
    }
    public FacultyDetails(long facultyId, Employee employee, Serializable domain, Byte quota, String facultyType, Set batchSessions, Set batches) {
       this.facultyId = facultyId;
       this.employee = employee;
       this.domain = domain;
       this.quota = quota;
       this.facultyType = facultyType;
       this.batchSessions = batchSessions;
       this.batches = batches;
    }
   
    public long getFacultyId() {
        return this.facultyId;
    }
    
    public void setFacultyId(long facultyId) {
        this.facultyId = facultyId;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public Serializable getDomain() {
        return this.domain;
    }
    
    public void setDomain(Serializable domain) {
        this.domain = domain;
    }
    public Byte getQuota() {
        return this.quota;
    }
    
    public void setQuota(Byte quota) {
        this.quota = quota;
    }
    public String getFacultyType() {
        return this.facultyType;
    }
    
    public void setFacultyType(String facultyType) {
        this.facultyType = facultyType;
    }
    public Set getBatchSessions() {
        return this.batchSessions;
    }
    
    public void setBatchSessions(Set batchSessions) {
        this.batchSessions = batchSessions;
    }
    public Set getBatches() {
        return this.batches;
    }
    
    public void setBatches(Set batches) {
        this.batches = batches;
    }




}


