package com.aprotrain.sl.dal.entity;
// Generated Mar 27, 2015 2:04:37 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Faculty generated by hbm2java
 */
public class Faculty  implements java.io.Serializable {


     private int facultyId;
     private Employee employee;
     private Serializable domain;
     private Set batches = new HashSet(0);

    public Faculty() {
    }

	
    public Faculty(int facultyId) {
        this.facultyId = facultyId;
    }
    public Faculty(int facultyId, Employee employee, Serializable domain, Set batches) {
       this.facultyId = facultyId;
       this.employee = employee;
       this.domain = domain;
       this.batches = batches;
    }
   
    public int getFacultyId() {
        return this.facultyId;
    }
    
    public void setFacultyId(int facultyId) {
        this.facultyId = facultyId;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public Serializable getDomain() {
        return this.domain;
    }
    
    public void setDomain(Serializable domain) {
        this.domain = domain;
    }
    public Set getBatches() {
        return this.batches;
    }
    
    public void setBatches(Set batches) {
        this.batches = batches;
    }




}


