package com.aprotrain.sl.dal.entity;
// Generated Apr 15, 2015 8:50:37 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Room generated by hbm2java
 */
public class Room  implements java.io.Serializable {


     private byte roomId;
     private Location location;
     private Serializable roomName;
     private Serializable remarks;
     private Byte roomType;

    public Room() {
    }

	
    public Room(byte roomId) {
        this.roomId = roomId;
    }
    public Room(byte roomId, Location location, Serializable roomName, Serializable remarks, Byte roomType) {
       this.roomId = roomId;
       this.location = location;
       this.roomName = roomName;
       this.remarks = remarks;
       this.roomType = roomType;
    }
   
    public byte getRoomId() {
        return this.roomId;
    }
    
    public void setRoomId(byte roomId) {
        this.roomId = roomId;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public Serializable getRoomName() {
        return this.roomName;
    }
    
    public void setRoomName(Serializable roomName) {
        this.roomName = roomName;
    }
    public Serializable getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(Serializable remarks) {
        this.remarks = remarks;
    }
    public Byte getRoomType() {
        return this.roomType;
    }
    
    public void setRoomType(Byte roomType) {
        this.roomType = roomType;
    }




}


