package com.aprotrain.sl.dal.entity;
// Generated Apr 15, 2015 8:50:37 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * StudentUpgradeHistory generated by hbm2java
 */
public class StudentUpgradeHistory  implements java.io.Serializable {


     private long studentUpgradeId;
     private Long studentId;
     private Serializable fromCourse;
     private Serializable toCourse;

    public StudentUpgradeHistory() {
    }

	
    public StudentUpgradeHistory(long studentUpgradeId) {
        this.studentUpgradeId = studentUpgradeId;
    }
    public StudentUpgradeHistory(long studentUpgradeId, Long studentId, Serializable fromCourse, Serializable toCourse) {
       this.studentUpgradeId = studentUpgradeId;
       this.studentId = studentId;
       this.fromCourse = fromCourse;
       this.toCourse = toCourse;
    }
   
    public long getStudentUpgradeId() {
        return this.studentUpgradeId;
    }
    
    public void setStudentUpgradeId(long studentUpgradeId) {
        this.studentUpgradeId = studentUpgradeId;
    }
    public Long getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }
    public Serializable getFromCourse() {
        return this.fromCourse;
    }
    
    public void setFromCourse(Serializable fromCourse) {
        this.fromCourse = fromCourse;
    }
    public Serializable getToCourse() {
        return this.toCourse;
    }
    
    public void setToCourse(Serializable toCourse) {
        this.toCourse = toCourse;
    }




}


