package com.aprotrain.sl.dal.entity;
// Generated Apr 18, 2015 3:08:48 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * StudentTransferHistory generated by hbm2java
 */
public class StudentTransferHistory  implements java.io.Serializable {


     private long transferId;
     private Student student;
     private Long fromClass;
     private Long toClass;
     private Serializable transferDate;
     private Serializable remarks;

    public StudentTransferHistory() {
    }

	
    public StudentTransferHistory(long transferId) {
        this.transferId = transferId;
    }
    public StudentTransferHistory(long transferId, Student student, Long fromClass, Long toClass, Serializable transferDate, Serializable remarks) {
       this.transferId = transferId;
       this.student = student;
       this.fromClass = fromClass;
       this.toClass = toClass;
       this.transferDate = transferDate;
       this.remarks = remarks;
    }
   
    public long getTransferId() {
        return this.transferId;
    }
    
    public void setTransferId(long transferId) {
        this.transferId = transferId;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Long getFromClass() {
        return this.fromClass;
    }
    
    public void setFromClass(Long fromClass) {
        this.fromClass = fromClass;
    }
    public Long getToClass() {
        return this.toClass;
    }
    
    public void setToClass(Long toClass) {
        this.toClass = toClass;
    }
    public Serializable getTransferDate() {
        return this.transferDate;
    }
    
    public void setTransferDate(Serializable transferDate) {
        this.transferDate = transferDate;
    }
    public Serializable getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(Serializable remarks) {
        this.remarks = remarks;
    }




}


