package com.aprotrain.sl.dal.entity;
// Generated Apr 17, 2015 12:45:39 AM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private long studentId;
     private Course course;
     private String rollnumber;
     private long initClass;
     private long currentClass;
     private String rollPortal;
     private Short gender;
     private Serializable dateOfBirth;
     private Serializable mobilePhone;
     private Serializable homePhone;
     private Serializable contactPhone;
     private String email;
     private Serializable address1;
     private Serializable address2;
     private Serializable joiningDate;
     private Serializable otherSchool;
     private Serializable remarks;
     private String promotion;
     private Serializable image;
     private String upgrade1;
     private String upgrade2;
     private Serializable finishDate;
     private Serializable finishRemarks;
     private Serializable dropoutDate;
     private Serializable dropoutPaymentMethod;
     private Serializable dropoutRemarks;
     private Serializable dropoutFillingDate;

    public Student() {
    }

	
    public Student(long studentId, String rollnumber, long initClass, long currentClass, String rollPortal, Serializable dateOfBirth, Serializable mobilePhone, Serializable homePhone, Serializable contactPhone) {
        this.studentId = studentId;
        this.rollnumber = rollnumber;
        this.initClass = initClass;
        this.currentClass = currentClass;
        this.rollPortal = rollPortal;
        this.dateOfBirth = dateOfBirth;
        this.mobilePhone = mobilePhone;
        this.homePhone = homePhone;
        this.contactPhone = contactPhone;
    }
    public Student(long studentId, Course course, String rollnumber, long initClass, long currentClass, String rollPortal, Short gender, Serializable dateOfBirth, Serializable mobilePhone, Serializable homePhone, Serializable contactPhone, String email, Serializable address1, Serializable address2, Serializable joiningDate, Serializable otherSchool, Serializable remarks, String promotion, Serializable image, String upgrade1, String upgrade2, Serializable finishDate, Serializable finishRemarks, Serializable dropoutDate, Serializable dropoutPaymentMethod, Serializable dropoutRemarks, Serializable dropoutFillingDate) {
       this.studentId = studentId;
       this.course = course;
       this.rollnumber = rollnumber;
       this.initClass = initClass;
       this.currentClass = currentClass;
       this.rollPortal = rollPortal;
       this.gender = gender;
       this.dateOfBirth = dateOfBirth;
       this.mobilePhone = mobilePhone;
       this.homePhone = homePhone;
       this.contactPhone = contactPhone;
       this.email = email;
       this.address1 = address1;
       this.address2 = address2;
       this.joiningDate = joiningDate;
       this.otherSchool = otherSchool;
       this.remarks = remarks;
       this.promotion = promotion;
       this.image = image;
       this.upgrade1 = upgrade1;
       this.upgrade2 = upgrade2;
       this.finishDate = finishDate;
       this.finishRemarks = finishRemarks;
       this.dropoutDate = dropoutDate;
       this.dropoutPaymentMethod = dropoutPaymentMethod;
       this.dropoutRemarks = dropoutRemarks;
       this.dropoutFillingDate = dropoutFillingDate;
    }
   
    public long getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(long studentId) {
        this.studentId = studentId;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public String getRollnumber() {
        return this.rollnumber;
    }
    
    public void setRollnumber(String rollnumber) {
        this.rollnumber = rollnumber;
    }
    public long getInitClass() {
        return this.initClass;
    }
    
    public void setInitClass(long initClass) {
        this.initClass = initClass;
    }
    public long getCurrentClass() {
        return this.currentClass;
    }
    
    public void setCurrentClass(long currentClass) {
        this.currentClass = currentClass;
    }
    public String getRollPortal() {
        return this.rollPortal;
    }
    
    public void setRollPortal(String rollPortal) {
        this.rollPortal = rollPortal;
    }
    public Short getGender() {
        return this.gender;
    }
    
    public void setGender(Short gender) {
        this.gender = gender;
    }
    public Serializable getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Serializable dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public Serializable getMobilePhone() {
        return this.mobilePhone;
    }
    
    public void setMobilePhone(Serializable mobilePhone) {
        this.mobilePhone = mobilePhone;
    }
    public Serializable getHomePhone() {
        return this.homePhone;
    }
    
    public void setHomePhone(Serializable homePhone) {
        this.homePhone = homePhone;
    }
    public Serializable getContactPhone() {
        return this.contactPhone;
    }
    
    public void setContactPhone(Serializable contactPhone) {
        this.contactPhone = contactPhone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Serializable getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(Serializable address1) {
        this.address1 = address1;
    }
    public Serializable getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(Serializable address2) {
        this.address2 = address2;
    }
    public Serializable getJoiningDate() {
        return this.joiningDate;
    }
    
    public void setJoiningDate(Serializable joiningDate) {
        this.joiningDate = joiningDate;
    }
    public Serializable getOtherSchool() {
        return this.otherSchool;
    }
    
    public void setOtherSchool(Serializable otherSchool) {
        this.otherSchool = otherSchool;
    }
    public Serializable getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(Serializable remarks) {
        this.remarks = remarks;
    }
    public String getPromotion() {
        return this.promotion;
    }
    
    public void setPromotion(String promotion) {
        this.promotion = promotion;
    }
    public Serializable getImage() {
        return this.image;
    }
    
    public void setImage(Serializable image) {
        this.image = image;
    }
    public String getUpgrade1() {
        return this.upgrade1;
    }
    
    public void setUpgrade1(String upgrade1) {
        this.upgrade1 = upgrade1;
    }
    public String getUpgrade2() {
        return this.upgrade2;
    }
    
    public void setUpgrade2(String upgrade2) {
        this.upgrade2 = upgrade2;
    }
    public Serializable getFinishDate() {
        return this.finishDate;
    }
    
    public void setFinishDate(Serializable finishDate) {
        this.finishDate = finishDate;
    }
    public Serializable getFinishRemarks() {
        return this.finishRemarks;
    }
    
    public void setFinishRemarks(Serializable finishRemarks) {
        this.finishRemarks = finishRemarks;
    }
    public Serializable getDropoutDate() {
        return this.dropoutDate;
    }
    
    public void setDropoutDate(Serializable dropoutDate) {
        this.dropoutDate = dropoutDate;
    }
    public Serializable getDropoutPaymentMethod() {
        return this.dropoutPaymentMethod;
    }
    
    public void setDropoutPaymentMethod(Serializable dropoutPaymentMethod) {
        this.dropoutPaymentMethod = dropoutPaymentMethod;
    }
    public Serializable getDropoutRemarks() {
        return this.dropoutRemarks;
    }
    
    public void setDropoutRemarks(Serializable dropoutRemarks) {
        this.dropoutRemarks = dropoutRemarks;
    }
    public Serializable getDropoutFillingDate() {
        return this.dropoutFillingDate;
    }
    
    public void setDropoutFillingDate(Serializable dropoutFillingDate) {
        this.dropoutFillingDate = dropoutFillingDate;
    }




}


