package com.aprotrain.sl.dal.entity;
// Generated Apr 15, 2015 8:50:37 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private long studentId;
     private ClassUnit classUnitByInitClass;
     private ClassUnit classUnitByCurrentClass;
     private Course course;
     private String rollnumber;
     private String rollPortal;
     private Short gender;
     private String dateOfBirth;
     private String mobilePhone;
     private String homePhone;
     private String contactPhone;
     private String email;
     private String address1;
     private String address2;
     private String joiningDate;
     private String otherSchool;
     private String remarks;
     private String promotion;
     private String image;
     private String upgrade1;
     private String upgrade2;
     private String finishDate;
     private String finishRemarks;
     private String dropoutDate;
     private String dropoutPaymentMethod;
     private String dropoutRemarks;
     private String dropoutFillingDate;
     private Set batchStudentLists = new HashSet(0);
     private Set examAttendances = new HashSet(0);
     private Set studentTransferHistories = new HashSet(0);

    public Student() {
    }

	
    public Student(long studentId, ClassUnit classUnitByInitClass, ClassUnit classUnitByCurrentClass, String rollnumber, String rollPortal, String dateOfBirth, String mobilePhone, String homePhone, String contactPhone) {
        this.studentId = studentId;
        this.classUnitByInitClass = classUnitByInitClass;
        this.classUnitByCurrentClass = classUnitByCurrentClass;
        this.rollnumber = rollnumber;
        this.rollPortal = rollPortal;
        this.dateOfBirth = dateOfBirth;
        this.mobilePhone = mobilePhone;
        this.homePhone = homePhone;
        this.contactPhone = contactPhone;
    }
    public Student(long studentId, ClassUnit classUnitByInitClass, ClassUnit classUnitByCurrentClass, Course course, String rollnumber, String rollPortal, Short gender, String dateOfBirth, String mobilePhone, String homePhone, String contactPhone, String email, String address1, String address2, String joiningDate, String otherSchool, String remarks, String promotion, String image, String upgrade1, String upgrade2, String finishDate, String finishRemarks, String dropoutDate, String dropoutPaymentMethod, String dropoutRemarks, String dropoutFillingDate, Set batchStudentLists, Set examAttendances, Set studentTransferHistories) {
       this.studentId = studentId;
       this.classUnitByInitClass = classUnitByInitClass;
       this.classUnitByCurrentClass = classUnitByCurrentClass;
       this.course = course;
       this.rollnumber = rollnumber;
       this.rollPortal = rollPortal;
       this.gender = gender;
       this.dateOfBirth = dateOfBirth;
       this.mobilePhone = mobilePhone;
       this.homePhone = homePhone;
       this.contactPhone = contactPhone;
       this.email = email;
       this.address1 = address1;
       this.address2 = address2;
       this.joiningDate = joiningDate;
       this.otherSchool = otherSchool;
       this.remarks = remarks;
       this.promotion = promotion;
       this.image = image;
       this.upgrade1 = upgrade1;
       this.upgrade2 = upgrade2;
       this.finishDate = finishDate;
       this.finishRemarks = finishRemarks;
       this.dropoutDate = dropoutDate;
       this.dropoutPaymentMethod = dropoutPaymentMethod;
       this.dropoutRemarks = dropoutRemarks;
       this.dropoutFillingDate = dropoutFillingDate;
       this.batchStudentLists = batchStudentLists;
       this.examAttendances = examAttendances;
       this.studentTransferHistories = studentTransferHistories;
    }
   
    public long getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(long studentId) {
        this.studentId = studentId;
    }
    public ClassUnit getClassUnitByInitClass() {
        return this.classUnitByInitClass;
    }
    
    public void setClassUnitByInitClass(ClassUnit classUnitByInitClass) {
        this.classUnitByInitClass = classUnitByInitClass;
    }
    public ClassUnit getClassUnitByCurrentClass() {
        return this.classUnitByCurrentClass;
    }
    
    public void setClassUnitByCurrentClass(ClassUnit classUnitByCurrentClass) {
        this.classUnitByCurrentClass = classUnitByCurrentClass;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public String getRollnumber() {
        return this.rollnumber;
    }
    
    public void setRollnumber(String rollnumber) {
        this.rollnumber = rollnumber;
    }
    public String getRollPortal() {
        return this.rollPortal;
    }
    
    public void setRollPortal(String rollPortal) {
        this.rollPortal = rollPortal;
    }
    public Short getGender() {
        return this.gender;
    }
    
    public void setGender(Short gender) {
        this.gender = gender;
    }
    public String getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(String dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getMobilePhone() {
        return this.mobilePhone;
    }
    
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }
    public String getHomePhone() {
        return this.homePhone;
    }
    
    public void setHomePhone(String homePhone) {
        this.homePhone = homePhone;
    }
    public String getContactPhone() {
        return this.contactPhone;
    }
    
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getJoiningDate() {
        return this.joiningDate;
    }
    
    public void setJoiningDate(String joiningDate) {
        this.joiningDate = joiningDate;
    }
    public String getOtherSchool() {
        return this.otherSchool;
    }
    
    public void setOtherSchool(String otherSchool) {
        this.otherSchool = otherSchool;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public String getPromotion() {
        return this.promotion;
    }
    
    public void setPromotion(String promotion) {
        this.promotion = promotion;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getUpgrade1() {
        return this.upgrade1;
    }
    
    public void setUpgrade1(String upgrade1) {
        this.upgrade1 = upgrade1;
    }
    public String getUpgrade2() {
        return this.upgrade2;
    }
    
    public void setUpgrade2(String upgrade2) {
        this.upgrade2 = upgrade2;
    }
    public String getFinishDate() {
        return this.finishDate;
    }
    
    public void setFinishDate(String finishDate) {
        this.finishDate = finishDate;
    }
    public String getFinishRemarks() {
        return this.finishRemarks;
    }
    
    public void setFinishRemarks(String finishRemarks) {
        this.finishRemarks = finishRemarks;
    }
    public String getDropoutDate() {
        return this.dropoutDate;
    }
    
    public void setDropoutDate(String dropoutDate) {
        this.dropoutDate = dropoutDate;
    }
    public String getDropoutPaymentMethod() {
        return this.dropoutPaymentMethod;
    }
    
    public void setDropoutPaymentMethod(String dropoutPaymentMethod) {
        this.dropoutPaymentMethod = dropoutPaymentMethod;
    }
    public String getDropoutRemarks() {
        return this.dropoutRemarks;
    }
    
    public void setDropoutRemarks(String dropoutRemarks) {
        this.dropoutRemarks = dropoutRemarks;
    }
    public String getDropoutFillingDate() {
        return this.dropoutFillingDate;
    }
    
    public void setDropoutFillingDate(String dropoutFillingDate) {
        this.dropoutFillingDate = dropoutFillingDate;
    }
    public Set getBatchStudentLists() {
        return this.batchStudentLists;
    }
    
    public void setBatchStudentLists(Set batchStudentLists) {
        this.batchStudentLists = batchStudentLists;
    }
    public Set getExamAttendances() {
        return this.examAttendances;
    }
    
    public void setExamAttendances(Set examAttendances) {
        this.examAttendances = examAttendances;
    }
    public Set getStudentTransferHistories() {
        return this.studentTransferHistories;
    }
    
    public void setStudentTransferHistories(Set studentTransferHistories) {
        this.studentTransferHistories = studentTransferHistories;
    }




}


