package com.aprotrain.sl.dal.entity;
// Generated Mar 27, 2015 2:04:37 PM by Hibernate Tools 4.3.1



/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private int studentId;
     private Clazz clazzByCurrentClass;
     private Clazz clazzByInitClass;
     private String rollnumber;

    public Student() {
    }

	
    public Student(int studentId) {
        this.studentId = studentId;
    }
    public Student(int studentId, Clazz clazzByCurrentClass, Clazz clazzByInitClass, String rollnumber) {
       this.studentId = studentId;
       this.clazzByCurrentClass = clazzByCurrentClass;
       this.clazzByInitClass = clazzByInitClass;
       this.rollnumber = rollnumber;
    }
   
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
    public Clazz getClazzByCurrentClass() {
        return this.clazzByCurrentClass;
    }
    
    public void setClazzByCurrentClass(Clazz clazzByCurrentClass) {
        this.clazzByCurrentClass = clazzByCurrentClass;
    }
    public Clazz getClazzByInitClass() {
        return this.clazzByInitClass;
    }
    
    public void setClazzByInitClass(Clazz clazzByInitClass) {
        this.clazzByInitClass = clazzByInitClass;
    }
    public String getRollnumber() {
        return this.rollnumber;
    }
    
    public void setRollnumber(String rollnumber) {
        this.rollnumber = rollnumber;
    }




}


