package com.aprotrain.sl.dal.entity;
// Generated Apr 17, 2015 12:45:39 AM by Hibernate Tools 4.3.1



/**
 * Subject generated by hbm2java
 */
public class Subject  implements java.io.Serializable {


     private long subjectId;
     private Course course;
     private String subjectCode;
     private String title;
     private Byte semeter;
     private Byte subjectOrder;
     private Byte totalSession;

    public Subject() {
    }

	
    public Subject(long subjectId) {
        this.subjectId = subjectId;
    }
    public Subject(long subjectId, Course course, String subjectCode, String title, Byte semeter, Byte subjectOrder, Byte totalSession) {
       this.subjectId = subjectId;
       this.course = course;
       this.subjectCode = subjectCode;
       this.title = title;
       this.semeter = semeter;
       this.subjectOrder = subjectOrder;
       this.totalSession = totalSession;
    }
   
    public long getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(long subjectId) {
        this.subjectId = subjectId;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public String getSubjectCode() {
        return this.subjectCode;
    }
    
    public void setSubjectCode(String subjectCode) {
        this.subjectCode = subjectCode;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Byte getSemeter() {
        return this.semeter;
    }
    
    public void setSemeter(Byte semeter) {
        this.semeter = semeter;
    }
    public Byte getSubjectOrder() {
        return this.subjectOrder;
    }
    
    public void setSubjectOrder(Byte subjectOrder) {
        this.subjectOrder = subjectOrder;
    }
    public Byte getTotalSession() {
        return this.totalSession;
    }
    
    public void setTotalSession(Byte totalSession) {
        this.totalSession = totalSession;
    }




}


