package com.aprotrain.sl.dal.entity;
// Generated Apr 15, 2015 8:50:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Subject generated by hbm2java
 */
public class Subject  implements java.io.Serializable {


     private long subjectId;
     private Course course;
     private String subjectCode;
     private String title;
     private Byte semeter;
     private Byte subjectOrder;
     private Byte totalSession;
     private Set exams = new HashSet(0);
     private Set batches = new HashSet(0);

    public Subject() {
    }

	
    public Subject(long subjectId) {
        this.subjectId = subjectId;
    }
    public Subject(long subjectId, Course course, String subjectCode, String title, Byte semeter, Byte subjectOrder, Byte totalSession, Set exams, Set batches) {
       this.subjectId = subjectId;
       this.course = course;
       this.subjectCode = subjectCode;
       this.title = title;
       this.semeter = semeter;
       this.subjectOrder = subjectOrder;
       this.totalSession = totalSession;
       this.exams = exams;
       this.batches = batches;
    }
   
    public long getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(long subjectId) {
        this.subjectId = subjectId;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public String getSubjectCode() {
        return this.subjectCode;
    }
    
    public void setSubjectCode(String subjectCode) {
        this.subjectCode = subjectCode;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Byte getSemeter() {
        return this.semeter;
    }
    
    public void setSemeter(Byte semeter) {
        this.semeter = semeter;
    }
    public Byte getSubjectOrder() {
        return this.subjectOrder;
    }
    
    public void setSubjectOrder(Byte subjectOrder) {
        this.subjectOrder = subjectOrder;
    }
    public Byte getTotalSession() {
        return this.totalSession;
    }
    
    public void setTotalSession(Byte totalSession) {
        this.totalSession = totalSession;
    }
    public Set getExams() {
        return this.exams;
    }
    
    public void setExams(Set exams) {
        this.exams = exams;
    }
    public Set getBatches() {
        return this.batches;
    }
    
    public void setBatches(Set batches) {
        this.batches = batches;
    }




}


