package com.aprotrain.sl.dal.entity;
// Generated Mar 27, 2015 2:04:37 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Subject generated by hbm2java
 */
public class Subject  implements java.io.Serializable {


     private int subjectId;
     private Course course;
     private Serializable subjectCode;
     private Serializable title;
     private Short semeter;
     private Short subjectOrder;
     private Integer subjectHour;
     private Set batches = new HashSet(0);

    public Subject() {
    }

	
    public Subject(int subjectId) {
        this.subjectId = subjectId;
    }
    public Subject(int subjectId, Course course, Serializable subjectCode, Serializable title, Short semeter, Short subjectOrder, Integer subjectHour, Set batches) {
       this.subjectId = subjectId;
       this.course = course;
       this.subjectCode = subjectCode;
       this.title = title;
       this.semeter = semeter;
       this.subjectOrder = subjectOrder;
       this.subjectHour = subjectHour;
       this.batches = batches;
    }
   
    public int getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(int subjectId) {
        this.subjectId = subjectId;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public Serializable getSubjectCode() {
        return this.subjectCode;
    }
    
    public void setSubjectCode(Serializable subjectCode) {
        this.subjectCode = subjectCode;
    }
    public Serializable getTitle() {
        return this.title;
    }
    
    public void setTitle(Serializable title) {
        this.title = title;
    }
    public Short getSemeter() {
        return this.semeter;
    }
    
    public void setSemeter(Short semeter) {
        this.semeter = semeter;
    }
    public Short getSubjectOrder() {
        return this.subjectOrder;
    }
    
    public void setSubjectOrder(Short subjectOrder) {
        this.subjectOrder = subjectOrder;
    }
    public Integer getSubjectHour() {
        return this.subjectHour;
    }
    
    public void setSubjectHour(Integer subjectHour) {
        this.subjectHour = subjectHour;
    }
    public Set getBatches() {
        return this.batches;
    }
    
    public void setBatches(Set batches) {
        this.batches = batches;
    }




}


